### ISSUE TITLE
feat: show which tag is being released

### ISSUE THREAD

**Issue by AndersDJohnson** [target/captains-log#125]
**Is your feature request related to a problem? Please describe.**
We love Captain's Log and would find value in being able to use it to announce release candidates as well as full production release, but we're not sure if it will be easy to tell from the Slack message when it's being posted for a release candidate vs. a full production release.

**Describe the solution you'd like**
Perhaps we could get an option (or new default) to have the Slack message include the name of the tag being released.

**Describe alternatives you've considered**
🤷‍♂️ 

**Additional context**
n/a

**Comment by therynamo** [comment]
Hey @AndersDJohnson - I've been removed as a maintainer from this project - so I'm not sure who is doing active development anymore. 

I'm pretty sure that [`slack_message_heading`](https://target.github.io/captains-log/docs/configuration/base-config) would allow you to accomplish this. You'd basically grab the `tagID` from the `build` and then interpolate it into the `SLACK_MESSAGE_HEADING` env variable that Captain's Log looks for. 

If that isn't sufficient for your needs you can keep this open and maybe @rdmulford can take a peak? 👀
