### ISSUE TITLE
[enhancement] Bit Bucket Support

### ISSUE THREAD

**Issue by rockoo** [target/captains-log#27]
Is there any future plans to add Bit Bucket support?

**Comment by therynamo** [comment]
Hey @rockoo, thanks for your question!

Unfortunately at this time, our roadmap doesn't have any plans for other SCM tool support.

Theoretically, this would be a change to the foundation of Captain's Log, but a worthwhile one. I'd be happy to notify this thread if we do decide to go that route. 

Thanks again,
Theryn
