### ISSUE TITLE
feat: optionally ignore issue reference

### ISSUE THREAD

**Issue by AndersDJohnson** [target/captains-log#36]
We could support a syntax that would let us refer to issues in PRs, but ignore them for reporting to Captain's Log. Nice if you're working on an issue in multiple phases across multiple releases, and want to refer to it to help PR reviewers, but don't want to misleadingly broadcast it to Slack as completed.

Perhaps:
```
https://jira.example.com/browse/JIRA-123 <!-- no-captains-log -->
```

Example:

I am merely referring to this one but it won't be logged due to the comment after it https://jira.example.com/browse/JIRA-123  (view the source).

**Comment by therynamo** [comment]
I like this idea, pretty quick to implement too. Thanks for creating this issue @AndersDJohnson 👍
