### ISSUE TITLE
Feat: Jira Branch Name Convention

### ISSUE THREAD

**Issue by therynamo** [target/captains-log#41]
### Summary

Jira has a github integration that allows you to link a story to a pull request by using a _branch name_ convention. That looks something like `my-branch/JIRA-123` where `my-branch` is arbitrary and `JIRA-123` is the team and ticket number associated to the pull request. 

### Done When

- A user can leave no description or indication of a JIRA ticket in the pull request body, but use the branching convention and still have it show up in Captain's Log
- A user can leave **both** a JIRA ticket/Github Issue in the pull request body, and use the branching convention, which allows all associated tickets to show up in Captain's Log
- A user can leave neither and Captain's Log will *still* output the standard messaging.

**Comment by therynamo** [comment]
**Note:** We will most likely force the "forward slash" convention in order to be **sure** that the following is the string we wish to validate against the "JIRA regex".

**Comment by gfernandez-me** [comment]
https://jira.atlassian.com/browse/JRASERVER-40549
