### ISSUE TITLE
feat: support Jira issue in PR title

### ISSUE THREAD

**Issue by AndersDJohnson** [target/captains-log#47]
When using squash merging with [Jira Smart Commits](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html), the Jira issue may need to be referenced in the PR title. This way, it will end up in the commit message on the `master` branch once merged (since squash merges don't do a rollup of PR commit messages, nor include PR description). Then the Jira GitHub integration can see it and automatically transition the issue. Therefore we could consider looking for Jira issues in the PR title as well as the PR body.

```
feat: my new feature JIRA-123 #done
```

**Comment by therynamo** [comment]
Thanks for the issue @AndersDJohnson! We really appreciate it. 

A little history behind Captain's Log (as you very well may know). It was originally designed to help individuals stop needing to place Jira titles in their PR. This left more space for `conventional commit` and information about the actual pull request. Given that, I'm still not sure we want to directly support Jira issues in PR title. 

I do however have a solution for you. It won't pick it up in the title, but we know the Github Jira integration works the same way when creating and using a jira based branch name. This was resolved as of #41. Let me know if you feel it should be expanded on.
