### ISSUE TITLE
Support Concourse CI By Default

### ISSUE THREAD

**Issue by therynamo** [target/captains-log#48]
We want to offer out of the box solutions for multiple CI tools. Starting with [concourse](https://concourse-ci.org/) as it is an easy course of action for us, but we're open to more tools.

**Comment by therynamo** [comment]
I think with the addition of #55, we'll be able to support just about any CI out of the box now. 

Thoughts @jmccann? 💭

**Comment by jmccann** [comment]
Drone expects `PLUGIN_` prefix in envvars read for params passed in from `.drone.yml`.  So it's good to have that logic in there to continue to support it.  It also be nice though to check for variables not prefixed with `PLUGIN_`?

e.g. I'm thinking if another CI tool wanted to use this it'd make more sense to pass envvar `GITHUB_OWNER` rather then `PLUGIN_GITHUB_OWNER`.  So it'd be nice to support both.

**Comment by therynamo** [comment]
I agree, I think support for both is the right call. I'll make sure the external config supports `PLUGIN_` as well. 

As far as other CI tools, I would expect a migration to `.captains.yml` instead of providing that information in the build pipeline itself. I think that using the build file simplifies what is needed in the configuration in general. Most of the information in there is about `teams` and I don't think that is necessary to the overall build itself. It would, however, be pretty simple to add env support that isn't `PLUGIN_` based, if one did want to go that route.

**Comment by therynamo** [comment]
Okay, so I looked back over this. The `PLUGIN_` convention is still supported even in [this PR that externalizes the config L51](https://github.com/target/captains-log/pull/55/files#diff-9d9a6cd82f41984872a66a3ab0d440c4R65). The env vars will initialize first, and then the captains config, if there is one.
