### ISSUE TITLE
feat: ignore comments more obvious alias

### ISSUE THREAD

**Issue by AndersDJohnson** [target/captains-log#53]
We could support aliases to the `icl` and `ecl` ignore comments (#36) that are more obvious - like `ignore-captains-log` and `end-ignore-captains-log`. Right now people might put `icl`/`ecl` in their PR templates and then later on others may not know why it's there or for what tool.

**Comment by therynamo** [comment]
I had a similar experience. Since `icl` is so similar to `includes` I hesitated and was wondering what it actually meant. I think it is confusing enough that we can come up with a better shorthand and longhand expression.
