### ISSUE TITLE
Customizable "Title" Message

### ISSUE THREAD

**Issue by eskerber** [target/captains-log#54]
## Feature Request

A deployment may require more context than a static message that it has been deployed. A build number, an environment, or even whether the changelog indicates that something has actually been "deployed", depending on a projects workflow.

## Possible Solutions
In increasing complexity:

- An optional, static title defined in yaml
- An optional, scripted title that can be executed at build time (using a Git tag or file contents as input, for example)

(I may submit a PR, if I overcome my lifelong avoidance of JS 😄)

**Comment by therynamo** [comment]
Hey @eskerber, thanks for submitting an issue to Captain's Log! I think this is a reasonable feature to implement. Your _possible solutions_ are good starts, as well. 

The only concern I'd see is adding "more" to the configuration. Captain's Log is already pretty configuration heavy. This isn't necessarily a problem, I'm just wondering if maybe there is a less "static" way to provide that. 

All in all, I think having both static options, and dynamic options is the right call. Customization is the name of the game when it comes to tooling 😄. 

If you want to submit a PR, I can work through it with you. That may be the quickest way to get that out, or I can think something up and show you what it may look like. Whatever happens first we'll go with!

**Comment by therynamo** [comment]
@eskerber , I opened a pr for this ticket and we should be good to go here. 

I thought about it some more, and I think the dynamic nature of the title belongs in the configuration file itself, and not in Captain's Log. So what you can do with the above PR is you can set `slack_message_heading` to a value in your `.drone.yml` or even run a script to generate some text for you in the `drone` environment. This will allow you access to all of the build time information you'd like.

Let me know what you think and if this will work for you and your team. 

Thanks again for taking the time to make this feature request.
