### ISSUE TITLE
feat: Comment on issues and PRs with release information

### ISSUE THREAD

**Issue by kamranayub** [target/captains-log#76]
**Is your feature request related to a problem? Please describe.**

It's common to ask, "What version was this issue or PR fixed in?"

**Describe the solution you'd like**

Semantic Release does this via the https://github.com/semantic-release/github plug-in

It adds a comment and labels issues and PRs that are included in the release.

**Describe alternatives you've considered**

n/a

**Additional context**

Here's what it looks like:

https://github.com/semantic-release/github/pull/269

![image](https://user-images.githubusercontent.com/563819/83153670-d96c2980-a0c4-11ea-8d78-dd4d44f5c96f.png)

**Comment by therynamo** [comment]
Awesome suggestion @kamranayub! I would love to get this up and running. 

A few questions:

Would you expect the "npm package" to be added to the comment like in the above screenshot? For instance if a mono-repo were to publish, would we need the package version of that publish to be reported back to the PR of each package published in that release?

**Comment by AndersDJohnson** [comment]
@kamranayub This is a cool feature proposal!

Just wanted to show an existing approach that's supported natively in GitHub already, in case it helps in the interim until this feature is available.

If you go the commit URL for the merge commit on a PR, e.g., https://github.com/my-org/my-repo/commit/abc123, you can see all the tags in which it's included, which might correspond to a release:

![Screen Shot 2020-06-01 at 3 06 17 PM](https://user-images.githubusercontent.com/615381/83465695-5b987d00-a43a-11ea-8eaf-93b30c0a831d.png)
